services:

  Apps.Factory.PostgresClient:
    factory:
      class: ../Factory/PostgresClientFactory
      method: 'createConnection'
    arguments: 
      - '%env(POSTGRES_DB)%'
      - '%env(POSTGRES_USER)%'
      - '%env(POSTGRES_PASSWORD)%'
      - '%env(POSTGRES_PORT)%'
      - '%env(POSTGRES_HOST)%'

  Apps.Finder.ProductFinder:
    class: ../Query/PostgresProductFinder
    arguments:
      - '@Apps.Factory.PostgresClient'

  Apps.Controller.ListedProductsController:
    class: ../Controllers/ListedProductsController
    arguments:
      - '@Apps.Query.ListedProductsQueryHandler'

  Apps.Query.ListedProductsQueryHandler:
    class: ../../Application/Query/ListedProductsQueryHandler
    arguments:
      - '@Apps.Finder.ProductFinder'
      - '@Apps.Service.ProductListService'

  Apps.Service.ProductListService:
    class: ../../Application/Service/ProductListService
