services:

  Apps.Factory.PostgresClient:
    factory:
      class: ../Factory/PostgresClientFactory
      method: 'createConnection'
    arguments: 
      - '%env(POSTGRES_DB)%'
      - '%env(POSTGRES_USER)%'
      - '%env(POSTGRES_PASSWORD)%'
      - '%env(POSTGRES_PORT)%'
      - '%env(POSTGRES_HOST)%'

  Apps.Finder.ProductFinder:
    class: ../Query/PostgresProductFinder
    arguments:
      - '@Apps.Factory.PostgresClient'

  Apps.Controller.ListedProductsController:
    class: ../Controllers/ListedProductsController
    arguments:
      - '@Apps.Query.ListedProductsQueryHandler'
      - '@Apps.Service.SchemaValidatorService'

  Apps.Query.ListedProductsQueryHandler:
    class: ../../Application/Query/ListedProductsQueryHandler
    arguments:
      - '@Apps.Finder.ProductFinder'
      - '@Apps.Service.ProductListService'

  Apps.Scoring.SalesScoreStrategy:
    class: ../../Application/Service/SalesScoreStrategy
    tags: 
      - { name: 'score.strategy'}

  Apps.Scoring.SizeStockScoreStrategy:
    class: ../../Application/Service/SizeStockScoreStrategy
    tags: 
      - { name: 'score.strategy'}

  Apps.Service.ProductListService:
    class: ../../Application/Service/ProductListService
    arguments: ["!tagged score.strategy"]

  Apps.Service.SchemaValidatorService:
    class: ../../Application/Service/SchemaValidatorService
  