services:
  itx-backend-tool-api:
    build:
      target: dev
      context: .
      args:
        - test=false
    command: npm run dev:start:itx-backend-tool-api
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "5001:5001"
      - "9230:9230"
    depends_on:
      - postgres
    environment:
      - PORT=5001

  postgres:
    image: "postgres:latest"
    command: postgres -c default_transaction_isolation=serializable
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: itx_database
      POSTGRES_USER: itx_user
      POSTGRES_PASSWORD: itx_password
      POSTGRES_PORT: 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
