CREATE SCHEMA itx;

CREATE TABLE itx.product (
	id INTEGER PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

INSERT INTO itx.product (id, name) VALUES
	(1, 'V-NECH BASIC SHIRT'),
	(2, 'CONTRASTING FABRIC T-SHIRT'),
	(3, 'RAISED PRINT T-SHIRT'),
	(4, 'PLEATED T-SHIRT'),
	(5, 'CONTRASTING LACE T-SHIRT'),
	(6, 'SLOGAN T-SHIRT');
