openapi: 3.0.4
info:
  title: Product Sorting API
  description: API to sort a list of products based on dynamic weight criteria.
  contact:
    email: noeliacastrelo@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
tags:
  - name: status
    description: Application health endpoint.
  - name: products
    description: Operations related to products.
paths:
  /status:
    get:
      tags:
        - status
      summary: Health endpoint to check if the API is running.
      operationId: getStatus
      responses:
        '200':
          description: The API is running.
        '500':
          description: Internal server error.
  /v1/products/sort-order:
    post:
      tags:
        - products
      summary: Sorts a list of products based on the provided weight criteria.
      operationId: sortProducts
      requestBody:
        description: Weight criteria for product sorting.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeightCriteria'
      responses:
        '200':
          description: Successfully sorted list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductView'
        '400':
          description: Bad request.
        '404':
          description: Products not found.
        '500':
          description: Internal server error.
components:
  schemas:
    WeightCriteria:
      type: object
      description: Weight criteria for sorting products.
      properties:
        salesUnit:
          type: number
          format: float
          description: Weight assigned to the sales unit.
        stockRatio:
          type: number
          format: float
          description: Weight assigned to sizes stock ratio.
      required:
        - salesUnit
        - stockRatio
    ProductView:
      type: object
      description: View of product information.
      properties:
        id:
          type: integer
          description: Unique identifier of the product.
        name:
          type: string
          description: Name of the product.
        sales:
          type: integer
          description: Total number of unit sales for the product.
        sizeStock:
          type: array
          description: Stock information per product size.
          items:
            $ref: '#/components/schemas/SizeStockView'
      required:
        - id
        - name
        - sales
        - sizeStock
    SizeStockView:
      type: object
      description: View of the stock for a specific size.
      properties:
        size:
          type: string
          description: Size of the product.
        stock:
          type: integer